# ---------------------------------------------------------------------------------------------------------------------- #
# Install Nginx

- name: nginx_install
  ansible.builtin.apt:
    name: nginx

# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration files

- name: nginx_template_default
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - nginx_restart
    - nginx_restart_exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Prometheus exporter

- name: nginx_install_exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: nginx_service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: nginx_service_exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
# ---------------------------------------------------------------------------------------------------------------------- #
