- name: install Nginx
  ansible.builtin.apt:
    name: nginx

- name: Service Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Copy default
  ansible.builtin.copy:
    src: ./roles/nginx/files/default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Install Nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Service Nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
