# ---------------------------------------------------------------------------------------------------------------------- #
# Install Nginx

- name: nginx_install
  ansible.builtin.apt:
    name: nginx

# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration files

- name: nginx_template_default
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - nginx_restart
    - nginx_restart_exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Prometheus exporter

- name: nginx_install_exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: nginx_service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: nginx_service_exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
# ---------------------------------------------------------------------------------------------------------------------- #
# Update DNS records

- name: nginx_nsupdate
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ bind_secret_update }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[bind_host]['ansible_default_ipv4']['address'] }}"
    record: "www-{{ inventory_hostname[-1] }}"
    zone: "{{ domain }}"    
    type: "CNAME"
    value: "{{ inventory_hostname  }}"
    ttl: 604800
  no_log: true