# ---------------------------------------------------------------------------------------------------------------------- #
# Install Nginx

- name: install Nginx
  ansible.builtin.apt:
    name: nginx

# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration files

- name: Template default
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx
    - Restart Nginx exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Prometheus exporter

- name: Install Nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: Service Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Service Nginx exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
# ---------------------------------------------------------------------------------------------------------------------- #
