# ---------------------------------------------------------------------------------------------------------------------- #
# Install haproxy

- name: haproxy_install
  apt:
    name: haproxy

# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration files

- name: haproxy_template_cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    group: haproxy
    mode: '0640'
  notify:
    - haproxy_restart

# ---------------------------------------------------------------------------------------------------------------------- #
# Service haproxy

- name: haproxy_service
  service:
    name: haproxy
    state: started

# ---------------------------------------------------------------------------------------------------------------------- #
# Install exporter

- name: haproxy_install_exporter
  apt:
    name: 
      - prometheus-haproxy-exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Copy exporter conf file

- name: haproxy_copy_exporter
  copy:
    src: prometheus-haproxy-exporter
    dest: /etc/default/prometheus-haproxy-exporter
  notify:
    - haproxy_restart_exporter


# ---------------------------------------------------------------------------------------------------------------------- #
# Service exporter

- name: haproxy_service_exporter
  service:
    name: prometheus-haproxy-exporter
    state: started


# ---------------------------------------------------------------------------------------------------------------------- #
# Update DNS records

- name: haproxy_nsupdate
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ bind_secret_update }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[bind_host]['ansible_default_ipv4']['address'] }}"
    record: "lb-{{ inventory_hostname[-1] }}"
    zone: "{{ domain }}"    
    type: "CNAME"
    value: "{{ inventory_hostname  }}"
    ttl: 604800
  no_log: true

# ---------------------------------------------------------------------------------------------------------------------- #
