# ---------------------------------------------------------------------------------------------------------------------- #
# Installing dependencies

- name: influxdb_directory_keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: influxdb_apt_key
  ansible.builtin.apt_key: 
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    keyring: /etc/apt/keyrings/influxdata-archive_compat.gpg
    state: present

- name: influxdb_apt_repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main

- name: influxdb_install
  apt:
    name:
      - influxdb
      - telegraf


# ---------------------------------------------------------------------------------------------------------------------- #
# Configuration files

- name: influxdb_copy_influxdb_conf
  copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
  notify:
    - influxdb_restart_influxdb

- name: influxdb_copy_telegraf_conf
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify:
    - influxdb_restart_telegraf

# ---------------------------------------------------------------------------------------------------------------------- #
# Backup

- name: influxdb_backup_directory
  file:
    state: directory
    path: "{{ backup_user_home }}/{{ item }}"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
    mode: '0700'
  no_log: true
  loop:
    - influxdb
    - restore

- name: influxdb_backup_cron
  template:
    src: influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup

# ---------------------------------------------------------------------------------------------------------------------- #
# Prometheus exporter

- name: influxdb_get_url_exporter
  ansible.builtin.get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin/influx_exporter
    mode: 0755
    owner: prometheus
    group: prometheus
  notify:
    - influxdb_restart_exporter

- name: influxdb_copy_exporter_unit
  copy:
    src: influxdb_exporter.service
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  register: service_result
  notify: 
    - influxdb_restart_exporter

- name: influxdb_command_daemon_reload
  command: systemctl daemon-reload
  when: service_result is changed

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: influxdb_service_influxdb
  service:
    name: influxdb
    enabled: true
    state: started

- name: influxdb_service_telegraf
  service:
    name: telegraf
    enabled: true
    state: started

- name: influxdb_service_exporter
  service: 
    name: prometheus-influxdb-stats-exporter.service
    state: started
    enabled: true

# ---------------------------------------------------------------------------------------------------------------------- #
# Update DNS records

- name: influxdb_nsupdate
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ bind_secret_update }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[bind_host]['ansible_default_ipv4']['address'] }}"
    record: "influxdb"
    zone: "{{ domain }}"    
    type: "CNAME"
    value: "{{ inventory_hostname  }}"
    ttl: 604800
  no_log: true
