# ---------------------------------------------------------------------------------------------------------------------- #
# Create volumes for grafana

- name: Grafana volumes
  file:
    state: directory
    path: "/opt/grafana/provisioning/{{ item }}"
  loop:
    - dashboards
    - datasources

- name: Template grafana.ini
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    mode: '0640'
  notify:
    - Restart Grafana

- name: Copy provider
  ansible.builtin.copy:
    src: provider.yaml
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify:
    - Restart Grafana

- name: Copy datasources
  copy:
    src: "{{ item }}-datasource.yaml"
    dest: "/opt/grafana/provisioning/datasources/{{ item }}-datasource.yaml"
  loop:
    - prometheus
    - influxdb-pinger
    - influxdb-syslog
  notify:
    - Restart Grafana  

- name: Copy Dashboards
  ansible.builtin.copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - main
    - syslog
    - mysql
  notify:
    - Restart Grafana

# ---------------------------------------------------------------------------------------------------------------------- #
# Create Grafana docker

- name: Grafana docker
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana  
    state: started
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    dns_servers: "{{ hostvars['pavroto-2']['ansible_default_ipv4']['address'] }}"

# ---------------------------------------------------------------------------------------------------------------------- #
