- name: Create /etc/apt/keyrings/
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Import Grafana GPG key
  ansible.builtin.apt_key: 
    url: https://apt.grafana.com/gpg.key
    keyring: /etc/apt/keyrings/grafana.gpg
    state: present

- name: Add Grafana repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main

- name: Install Grafana and dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https 
      - software-properties-common 
      - wget
      - grafana

- name: Copy grafana.ini
  ansible.builtin.copy:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
  notify:
    - Restart Grafana

- name: User Grafana
  community.grafana.grafana_user:
    url: "http://localhost:3000"
    name: "pavroto"
    login: "{{ grafana_user }}"
    password: "{{ grafana_password }}"
    is_admin: true
    url_username: "{{ grafana_user }}"
    url_password: "{{ grafana_url_password }}"
    email: "pavroto@{{ domain }}"
    state: present

#- name: Dashboard Grafana
#  grafana.grafana.grafana_dashboard:
#    dashboard: dashboard.json
#    grafana_url: http://localhost:3000
#    url_username: "{{ grafana_user }}"
#    url_password: "{{ grafana_url_password }}"
     
- name: Service Grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true
