# ---------------------------------------------------------------------------------------------------------------------- #
# Create volumes for grafana

- name: grafana_directory
  file:
    state: directory
    path: "/opt/grafana/provisioning/{{ item }}"
  loop:
    - dashboards
    - datasources

- name: grafana_template_grafana
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
    mode: '0640'
  notify:
    - grafana_restart

- name: grafana_copy_provider
  ansible.builtin.copy:
    src: provider.yaml
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify:
    - grafana_restart

- name: grafana_copy_datasource
  copy:
    src: "{{ item }}-datasource.yaml"
    dest: "/opt/grafana/provisioning/datasources/{{ item }}-datasource.yaml"
  loop:
    - prometheus
    - influxdb-pinger
    - influxdb-syslog
  notify:
    - grafana_restart  

- name: grafana_copy_dashboard
  ansible.builtin.copy:
    src: "{{ item }}.json"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}.json"
  loop:
    - main
    - syslog
    - mysql

# ---------------------------------------------------------------------------------------------------------------------- #
# Create Grafana docker

- name: grafana_docker_container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana  
    state: started
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    dns_servers: "{{ groups['dns_servers'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"

# ---------------------------------------------------------------------------------------------------------------------- #
