# ---------------------------------------------------------------------------------------------------------------------- #
# Install uWSGI

- name: Install uwsgi
  ansible.builtin.apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

# ---------------------------------------------------------------------------------------------------------------------- #
# Copy configuration file

- name: Copy agama.ini
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 600
  notify:
    - Restart uWSGI

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: Service uWSGI
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
# ---------------------------------------------------------------------------------------------------------------------- #
