{
 "title": "ica0002",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pinger",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Cloudflare",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "1.1.1.1" }
     ]
    },
    {
     "alias": "Google",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ],
     "tags": [
      { "key": "dst::tag", "operator": "=", "value": "8.8.8.8" }
     ]
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Bind9",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[1m]))",
     "legendFormat": "pavroto-1"
    },
    {
     "expr": "sum(rate(nginx_http_requests_total{instance=\"pavroto-2:9113\"}[1m]))",
     "legendFormat": "pavroto-2"
    }
   ]
  },
  {
   "title": "DNS queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])*60",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "pavroto-1 CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": " 100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"pavroto-1:9100\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pavroto-1 RAM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": " (1 - (node_memory_MemFree_bytes{instance=\"pavroto-1:9100\"} + node_memory_Cached_bytes{instance=\"pavroto-1:9100\"} + node_memory_Buffers_bytes{instance=\"pavroto-1:9100\"}) / node_memory_MemTotal_bytes{instance=\"pavroto-1:9100\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{instance}} {{server}}" }
   ]
  },
  {
   "title": "pavroto-2 CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": " 100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"pavroto-2:9100\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pavroto-2 CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": " 100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"pavroto-2:9100\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(influxdb_write_write_ok[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived State",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "pavroto-3 CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": " 100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"pavroto-3:9100\"}[5m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "pavroto-2 RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": " (1 - (node_memory_MemFree_bytes{instance=\"pavroto-3:9100\"} + node_memory_Cached_bytes{instance=\"pavroto-3:9100\"} + node_memory_Buffers_bytes{instance=\"pavroto-3:9100\"}) / node_memory_MemTotal_bytes{instance=\"pavroto-3:9100\"}) * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{instance=\"pavroto-1:9104\"}[1m]))",
     "legendFormat": "pavroto-1"
    },
    {
     "expr": "sum(rate(mysql_global_status_commands_total{instance=\"pavroto-2:9104\"}[1m]))",
     "legendFormat": "pavroto-2"
    }
   ]
  }
 ]
}