{
 "title": "MySQL",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{instance=\"pavroto-1:9104\"}[1m]))",
     "legendFormat": "pavroto-1"
    },
    {
     "expr": "sum(rate(mysql_global_status_commands_total{instance=\"pavroto-2:9104\"}[1m]))",
     "legendFormat": "pavroto-2"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Server ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Only",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO thread",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL thread",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}