# ---------------------------------------------------------------------------------------------------------------------- #
# Prepare required files 

- name: agama_directory_create
  file:
    state: directory
    path: /opt/agama/

- name: agama_download
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}"
    dest: "/opt/agama/{{ item }}"
  loop:
    - Dockerfile
    - agama.py


# ---------------------------------------------------------------------------------------------------------------------- #
# Create agama

- name: agama_image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
#  no_log: true

- name: agama_container
  community.docker.docker_container:
    name: agama
    image: agama
    state: started
    published_ports: "{{ agama_port }}:8000"
    env: 
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}.{{ domain }}/{{ mysql_database }}
    dns_servers: "{{ hostvars['pavroto-2']['ansible_default_ipv4']['address'] }}"

  
# ---------------------------------------------------------------------------------------------------------------------- #
