- name: init_restart_resolved
  service:
    name: systemd-resolved
    state: restarted

- name: init_restart_rsyslog
  service:
    name: rsyslog
    state: restarted

- name: init_command_chown_backup_directory
  command: "chown -R {{ backup_user }}:{{ backup_user }} {{ backup_user_home }}"
