- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Change backup directory permissions
  command: "chown -R {{ backup_user }}:{{ backup_user }} {{ backup_user_home }}"
