- name: Install MySQL
  ansible.builtin.apt:
    name: 
      - mysql-server
      - python3-pymysql

- name: Service MySQL
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Bind to public address
  ansible.builtin.copy:
    src: address.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf 
  notify:
    - Restart MySQL

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
