- name: Install MySQL
  ansible.builtin.apt:
    name: 
      - mysql-server
      - python3-pymysql

- name: Service MySQL
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Bind to public address
  ansible.builtin.copy:
    src: address.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf 
  notify:
    - Restart MySQL

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    host: "%"
    resource_limits: 
      MAX_USER_CONNECTIONS: 3
    priv: '*.*:PROCESS,REPLICATION CLIENT'
    login_unix_socket: /var/run/mysqld/mysqld.sock    

- name: Install MySQL exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter 

- name: Service MySQL exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true

- name: Template my.cnf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '0640' 
  notify:
    - Restart MySQL exporter
