- name: nginx_restart
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: nginx_restart_exporter
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: restarted
