# ---------------------------------------------------------------------------------------------------------------------- #
# Install dependencies

- name: Install fping
  apt:
    name: fping

# ---------------------------------------------------------------------------------------------------------------------- #
# Create system user

- name: Create system user pinger
  user:
    name: pinger
    system: true   

# ---------------------------------------------------------------------------------------------------------------------- #
# Install pinger script

- name: Copy pinger.sh
  copy:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    mode: 0755
  notify:
    - Restart pinger

# ---------------------------------------------------------------------------------------------------------------------- #
# Create configuration files, systemd units

- name: mkdir /etc/pinger/
  ansible.builtin.file:
    path: /etc/pinger/
    state: directory

- name: Copy pinger.conf
  copy:
    src: pinger.conf
    dest: /etc/pinger/pinger.conf
  notify:
    - Restart pinger

- name: Copy pinger.service
  copy:
    src: pinger.service
    dest: /etc/systemd/system/pinger.service
    mode: 0644
  register: service_result

- name: Command systemctl daemon-reload
  command: systemctl daemon-reload
  when: service_result is changed

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: Service pinger
  service:
    name: pinger
    state: started
    enabled: true
# ---------------------------------------------------------------------------------------------------------------------- #
