# ---------------------------------------------------------------------------------------------------------------------- #
# Install dependencies

- name: pinger_install_fping
  apt:
    name: fping

# ---------------------------------------------------------------------------------------------------------------------- #
# Create system user

- name: pinger_user
  user:
    name: pinger
    system: true   

# ---------------------------------------------------------------------------------------------------------------------- #
# Install pinger script

- name: pinger_copy_sh
  copy:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    mode: 0755
  notify:
    - pinger_restart

# ---------------------------------------------------------------------------------------------------------------------- #
# Create configuration files, systemd units

- name: pinger_directory
  ansible.builtin.file:
    path: /etc/pinger/
    state: directory

- name: pinger_template_conf
  template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify:
    - pinger_restart

- name: pinger_copy_unit
  copy:
    src: pinger.service
    dest: /etc/systemd/system/pinger.service
    mode: 0644
  notify:
    - pinger_restart
  register: service_result

- name: pinger_command_daemon_reload
  command: systemctl daemon-reload
  when: service_result is changed

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: pinger_service
  service:
    name: pinger
    state: started
    enabled: true
# ---------------------------------------------------------------------------------------------------------------------- #
