- name: influxdb_restart_influxdb
  service:
    name: influxdb
    state: restarted

- name: influxdb_restart_telegraf
  service:
    name: telegraf
    state: restarted

- name: influxdb_restart_exporter
  service:
    name: prometheus-influxdb-stats-exporter.service 
    state: restarted
