# ---------------------------------------------------------------------------------------------------------------------- #
# Install Keepalived

- name: keepalived_install
  apt:
    name: keepalived
# ---------------------------------------------------------------------------------------------------------------------- #
# Create keepalived groups and users

- name: keepalived_user
  user: 
    name: keepalived_script
    shell: /sbin/nologin

# ---------------------------------------------------------------------------------------------------------------------- #
# Keepalived script

- name: keepalived_copy_script
  copy:
    src: keepalived_script
    dest: /home/keepalived_script/keepalived_script 
    owner: keepalived_script
    group: keepalived_script
    mode: 0744
# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration

- name: keepalived_template_conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0640'
  notify:
    - keepalived_restart
  no_log: true

# ---------------------------------------------------------------------------------------------------------------------- #
# Service keepalived

- name: keepalived_service
  service:
    name: keepalived
    state: started
    enabled: true

# ---------------------------------------------------------------------------------------------------------------------- #
# Install exporter

- name: keepalived_install_exporter
  apt:
    deb: https://github.com/mehdy/keepalived-exporter/releases/download/v1.3.2/keepalived-exporter-1.3.2.linux-amd64.deb

# ---------------------------------------------------------------------------------------------------------------------- #
# Copy prometheus-keepalived-exporter.service

- name: keepalived_copy_exporter_service
  copy:
    src: prometheus-keepalived-exporter.service
    dest: /etc/systemd/system/prometheus-keepalived-exporter.service
  register: keepalived_copy_exporter_service
  notify:
    - keepalived_restart_exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Service exporter

- name: keepalived_command_daemon_reload
  command: systemctl daemon-reload
  when: keepalived_copy_exporter_service is changed

- name: keepalived_service_exporter
  service:
    name: prometheus-keepalived-exporter.service
    state: started
    enabled: true

# ---------------------------------------------------------------------------------------------------------------------- #
