# ---------------------------------------------------------------------------------------------------------------------- #
# Install Prometheus

- name: prometheus_install
  ansible.builtin.apt:
    name: 
      - prometheus

# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration files

- name: prometheus_template_yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - prometheus_restart

- name: prometheus_template_default
  ansible.builtin.template:
    src: prometheus.default.j2
    dest: /etc/default/prometheus
  notify:
    - prometheus_restart

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: prometheus_service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

# ---------------------------------------------------------------------------------------------------------------------- #
# Update DNS records

- name: prometheus_nsupdate
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ bind_secret_update }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[bind_host]['ansible_default_ipv4']['address'] }}"
    record: "prometheus"
    zone: "{{ domain }}"
    type: "CNAME"
    value: "{{ inventory_hostname }}"
    ttl: 604800
  no_log: true
