# ---------------------------------------------------------------------------------------------------------------------- #
# Install Prometheus

- name: Install Prometheus
  ansible.builtin.apt:
    name: 
      - prometheus

# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration files

- name: Template prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart Prometheus

- name: Template prometheus.default
  ansible.builtin.template:
    src: prometheus.default.j2
    dest: /etc/default/prometheus
  notify:
    - Restart Prometheus

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: Service Prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
# ---------------------------------------------------------------------------------------------------------------------- #
