- name: grafana_restart
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana  
    state: started
    restart: true
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"

