# ---------------------------------------------------------------------------------------------------------------------- #
# Install Docker

- name: Install Docker
  apt:
    name: 
      - docker.io
      - python3-docker

# ---------------------------------------------------------------------------------------------------------------------- #
# Service Docker

- name: Service Docker
  service:
    name: docker
    state: started

# ---------------------------------------------------------------------------------------------------------------------- #
