# ---------------------------------------------------------------------------------------------------------------------- #
# Install Bind

- name: bind_install
  ansible.builtin.apt:
    name: 
      - bind9

# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration files

- name: bind_template_named
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
    mode: '0640'
  loop:
    - options
    - local
  notify:
    - bind_restart

- name: bind_directory
  file:
    path: /var/cache/bind/
    state: directory
    owner: bind
    group: bind

- name: bind_template_domain
  ansible.builtin.template:
    src: "{{ item }}.db.j2"
    dest: "/var/cache/bind/{{ item }}.db"
    owner: bind
    group: bind
    force: false
  loop:
    - pavroto.ttu
    - ptr
  notify:
    - bind_restart_rndc
  when: inventory_hostname == bind_host

# ---------------------------------------------------------------------------------------------------------------------- #
# Prometheus exporter

- name: bind_install_exporter
  ansible.builtin.apt:
    name: 
      - prometheus-bind-exporter
      - libxml2

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: bind_service
  ansible.builtin.service:  
    name: bind9
    state: started
    enabled: true

- name: bind_service_exporter
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: started
# ---------------------------------------------------------------------------------------------------------------------- #
