- name: Install Bind9
  ansible.builtin.apt:
    name: 
      - bind9

- name: Service Bind9
  ansible.builtin.service:  
    name: bind9
    state: started
    enabled: true

- name: Template named.conf.
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
  notify:
    - Restart Bind9

- name: Template domain.db.j2
  ansible.builtin.template:
    src: domain.db.j2
    dest: /var/lib/bind/{{ domain }}.db
  notify:
    - rndc reload
