# ---------------------------------------------------------------------------------------------------------------------- #
# Install Bind

- name: Install Bind9
  ansible.builtin.apt:
    name: 
      - bind9

# ---------------------------------------------------------------------------------------------------------------------- #
# Template configuration files

- name: Template named.conf.
  ansible.builtin.template:
    src: named.conf.{{ item }}.j2
    dest: /etc/bind/named.conf.{{ item }}
  loop:
    - options
    - local
  notify:
    - Restart Bind9

- name: Template domain.db.j2
  ansible.builtin.template:
    src: domain.db.j2
    dest: /var/lib/bind/{{ domain }}.db
  notify:
    - rndc reload

# ---------------------------------------------------------------------------------------------------------------------- #
# Prometheus exporter

- name: Install Bind exporter
  ansible.builtin.apt:
    name: 
      - prometheus-bind-exporter
      - libxml2

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: Service Bind9
  ansible.builtin.service:  
    name: bind9
    state: started
    enabled: true

- name: Service Bind exporter
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: started
# ---------------------------------------------------------------------------------------------------------------------- #
