# ---------------------------------------------------------------------------------------------------------------------- #
# Debug sudo command
# NOTE! This task MUST BE BEFORE "Set a hostname" task.

- name: init_template_hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

# ---------------------------------------------------------------------------------------------------------------------- #
# Hostname

#- name: init_hostname
#  ansible.builtin.hostname:
#    name: "{{ inventory_hostname }}"

- name: init_template_hostname
  template:
    src: hostname.j2
    dest: /etc/hostname

# ---------------------------------------------------------------------------------------------------------------------- #
# Lecturers users

- name: init_user_juri
  ansible.builtin.user:
    name: juri
    comment: Juri Hudolejev

- name: init_user_roman
  ansible.builtin.user:
    name: roman
    comment: Roman Kuchin

- name: Set authorized key for juri
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys

- name: Set authorized key for roman
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/romankuchin.keys

# ---------------------------------------------------------------------------------------------------------------------- #
# Backup

- name: init_install_duplicity
  apt:
    name: 
      - duplicity

- name: init_user_backup
  user:
    name: "{{ backup_user }}"
    comment: Backup User
    home: "{{ backup_user_home }}"
    move_home: true
    generate_ssh_key: true
    ssh_key_file: "{{ backup_user_home }}/.ssh/id_rsa"
    ssh_key_type: rsa
    system: true
  notify:
    - init_command_chown_backup_directory

- name: init_template_known_hosts
  template:
    src: known_hosts.backup.j2
    dest: "{{ backup_user_home }}/.ssh/known_hosts"
    owner: backup
    group: backup
    mode: '0600'
  no_log: true

# ---------------------------------------------------------------------------------------------------------------------- #
# APT updates

- name: init_apt_update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: init_upgrade_ca_certificates
  ansible.builtin.apt:
    name: ca-certificates>=20211000*

- name: init_install_pip
  apt:
    name:
      - python3-pip

# ---------------------------------------------------------------------------------------------------------------------- #
# .bash_aliases

- name: init_copy_bash_aliases
  ansible.builtin.copy:
    src: ./roles/init/files/bash_aliases
    dest: /home/ubuntu/.bash_aliases
    owner: ubuntu
    group: ubuntu

# ---------------------------------------------------------------------------------------------------------------------- #
# DNS settings

- name: init_template_resolv
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  notify:
    - init_restart_resolved

- name: bind_install_dnspython
  pip:
    name:
      - dnspython

# ---------------------------------------------------------------------------------------------------------------------- #
# Rsyslog configuration

- name: init_template_telegraf_output
  template:
    src: telegraf-output.conf.j2
    dest: /etc/rsyslog.d/telegraf-output.conf
  notify:
    - init_restart_rsyslog

# ---------------------------------------------------------------------------------------------------------------------- #
# Prometheus exporter

- name: init_apt_node_exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter

# ---------------------------------------------------------------------------------------------------------------------- #
# Service

- name: init_service_node_exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true
# ---------------------------------------------------------------------------------------------------------------------- #

#- debug: msg="trigger Change backup directory permissions"
#  notify: Change backup directory permissions
#  changed_when: true 
