- name: Create user juri
  ansible.builtin.user:
    name: juri
    comment: Juri Hudolejev

- name: Create user roman
  ansible.builtin.user:
    name: roman
    comment: Roman Kuchin

- name: Set authorized key for juri
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys

- name: Set authorized key for roman
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/romankuchin.keys
