- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Create user juri
  ansible.builtin.user:
    name: juri
    comment: Juri Hudolejev

- name: Create user roman
  ansible.builtin.user:
    name: roman
    comment: Roman Kuchin

#- name: Set authorized key for juri
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Set authorized key for roman
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Add .bash_aliases to /home/ubuntu
  ansible.builtin.copy:
    src: ./roles/init/files/bash_aliases
    dest: /home/ubuntu/.bash_aliases
    owner: ubuntu
    group: ubuntu


# DNS settings
- name: Template resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf


# Monitoring tools.
- name: Install prometheus-node-exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter

- name: Service prometheus-node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true
